Feat/86: Add, edit, save, validate Height
thanhpd/OpenTracks-Winter-SOEN-6431_2024 pull request #57
Opened 2024-04-17 02:55 UTC by Gouthamsusarla

# Thanks for your contribution.

**Describe the pull request**
Allow users to add, edit, save and validate height

**Link to the issue**
rilling#86

2024-04-17 02:57 UTC, pranav687 approved these changes

2024-04-17 14:17 UTC, thanhpd requested changes

2024-04-17 14:17 UTC, thanhpd commented on src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
> +
The requirement:
Height: (feet or metric depending Settings->Default Units…)

=> You might need to also store the unit alongside the number, then in the getter function, you'll need to check the current default unit. If they both match, then return the number. If not, you'll need to perform unit conversion to convert the number to the correct unit.

Use getUnitSystem() in PreferencesUtils to get the current setting.

2024-04-17 14:17 UTC, thanhpd commented on src/main/res/xml/settings_profile.xml
> +    <EditTextPreference
The requirement:
Height: (feet or metric depending Settings->Default Units…)

My feedback:
Should add label indicating the unit (metre/m or foot/ft) in the dialog/text field. Use getUnitSystem() in PreferencesUtils to get the current setting.

2024-04-26 01:29 UTC, thanhpd approved these changes

2024-04-26 01:30 UTC, merged